### ISSUE TITLE
Does Searcher support chunked zim and separate idx directories?

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-lib#112]
I am wondering if `Searcher` has support over the following cases:

- chunked zim files (zimaa, zimab, etc.) with index embedded
- idx directory came with a non indexed zim file

I believe if supported, you just need to add a reader of chunked zim file to `Searcher`. But I don't think the second case is supported.

**Comment by mgautierfr** [comment]
> chunked zim files (zimaa, zimab, etc.) with index embedded

No. If the zim file is chunked, the embedded index can be in different chunks and xapian cannot handle it. So if a zim file is chunked, libzim pretends there is no embedded index inside. We could improve a bit libzim to pretends there is no index only if the index is actually in split in different chunks. (But I not sure about this, it would be confusing for user if sometime index is "inside" the zim and sometime not)

> idx directory came with a non indexed zim file

Searcher support this, you "just" have to create the `Searcher` with the idx directory as argument :
```
Searcher(const string& xapianDirectoryPath, Reader* reader, const string& humanReadableName);
``` 
- `reader` is a `Reader` for the zim associated to the idx. You can pass `NULL` to it but the search result will always return empty string for `get_snippet`  and `get_content`.
- `humanReadableName` is only use to generate search result html page. In your case, you can pass an empty string as you never use it (and cannot because you are compiling without ctpp2)

However, internal search code for embedded and external are totally separated. Multi-database search is not supported with external idx directory. (This is why there is not `add_idx_directory` method)
