### ISSUE TITLE
Better handling of search pagination parameters.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-lib#321]
For now, the pagination is handled using two parameters `start` and `end`. `end-start` being the `nb_element_per_page`.
If you go to the last page using the button added at end of the search page, `start` is `last_page_index * nb_element_per_page` and `end` is `number_of_result`. In this situation the `end-start` will be smaller that the original `nb_element_per_page`.
If we navigate again in the search pages, the page lengh is now smaller than original. (In worst case, only one element per page).

Instead of a `start`, `end` parameters, we should use a `start`, `pagelength` parameter. This way the `pagelength` is always the same. We must only change the `start` parameter to change page.

**Comment by MananJethwani** [comment]
I want to work on this

**Comment by MananJethwani** [comment]
can you elaborate a bit on what I should do.....as I can see I have 2 options either I can just change the request part in server.cpp to get the pagelength instead of end and calculate end accordingly(start+pagelength and some exceptional cases) or I could change request as well as searcher and search_rendered to take pagelength as an argument everywhere and make changes accordingle

**Comment by kelson42** [comment]
@mgautierfr @MananJethwani Should we notcloe this ticket?

**Comment by mgautierfr** [comment]
Yes.
