### ISSUE TITLE
taskbar should be inserted after charset definition

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-lib#322]
The kiwix-serve *taskbar* adds a bunch of content to the beginning of the `<head>` element rendering it **difficult** to place the `<meta charset />` element within the first 1024 characters of the page.

According to [the spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta), the charset element must be **inside the `<head />`** and **within the first 1024 bytes** of the content.

Given the following, **custom-crafted** HTML content

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My title</title>
  </head>
```

The library with the taskbar enabled would serve:

``` html
<!DOCTYPE html>
<html>
  <head><link type="text/css" href="/skin/jquery-ui/jquery-ui.min.css" rel="Stylesheet" />
<link type="text/css" href="/skin/jquery-ui/jquery-ui.theme.min.css" rel="Stylesheet" />
<link type="text/css" href="/skin/taskbar.css" rel="Stylesheet" />
<script type="text/javascript" src="/skin/jquery-ui/external/jquery/jquery.js"></script>
<script type="text/javascript" src="/skin/jquery-ui/jquery-ui.min.js"></script>
<script>
  var jk = jQuery.noConflict();
  jk(function() {
  jk( "#kiwixsearchbox" ).autocomplete({

  source: "/suggest?content=la_chaine_de_maths_et_tiques_fr_all_2020-02",
  dataType: "json",
  cache: false,

  select: function(event, ui) {
  jk( "#kiwixsearchbox" ).val(ui.item.value);
  jk( "#kiwixsearchform" ).submit();
  },

  });
  });

  /* cybook hack */
  if (navigator.userAgent.indexOf("bookeen/cybook") != -1) {
    jk("html").addClass("cybook");
  }
</script>
<script type="text/javascript" src="/skin/taskbar.js" async></script>
    <meta charset="utf-8">
    <title>My title</title>
  </head>
```
The taskbar payload is 984 bytes alone, leaving almost nothing and variable according to the ZIM name.

It's OK on this optimized html example but in many cases, the charset would not make it to the first 1024b, forcing the browser to restart rendering after eventually encountering a charset info. This is visible in the logs with Firefox

``` 
The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file. home.html:33
```

We could tackle this in several ways:

* require ZIM creators to to place their charset definition at the very beginning of their `<head />`. [documentation]
* parse content HTML in the library to find out the declared charset and set it in [`head_part.html`](https://github.com/kiwix/kiwix-lib/blob/master/static/templates/head_part.html) 😬
* consider/require ZIM creators to publish UTF-8 only (seems like `appendToFirstOccurence` kind of assumes it is) and simply had `<meta charset="utf-8">` to `head_part.html`.

**Notes:**

* `appendToFirstOccurence` seems either improperly named of incorrectly implemented. Should it be named `prependToFirstOccurence` or should the code but inserted at the end of `<head />` (hence appended)
* most browsers can be tricked by placing the charset on the root `<html />` element instead of the `<head />` but… it's just a workaround.

**Comment by kelson42** [comment]
Seems doable by just inserting before `<head/>` instead of after `<head>`.

**Comment by rgaudin** [comment]
@kelson42 wouldn't change a thing to insert before head and it would still be at the very beginning of the whole response.

**Comment by mgautierfr** [comment]
Inserting before `</head>` (so just before the end of the `<head>` tag) should keep everything in the head at the beginning of the file.

---

However, this issue makes me think about another way we could use to include the taskbar in the content. We could use a small js file in every article to modify the dom. This small (or not) script would always be the same name, a wellknown name (ie, `/clientScript.js` or something like that). Even if all articles in the zim file would try to include it, it would be not in the zim file, but provided by the client (kiwix-tools, android, macos, desktop client, ...). It would be to the js to modify the dom to add the taskbar, do ask for suggestions and so.

I see several pros for this:
- If we add the script tag in the html directly, we don't have to modify the html on the server to include the taskbar.
- The js/css would be cached by the browser, instead of being download several times (embedded in the html)
- The js could do more than add the taskbar, on native client, it could be use to parse the html, generate a table of content and send it to the native code using the appropriate way.
- Vendors, who already proxy kiwix-serve, could intercept the request to the js and provide their own. This way, they could use custom css, button, ... to integrate correctly with their system.

The main cons I see is that we need js compatible browser. This is the case for most of the browser in the market but some vendors may use
pretty old browser or specific device that doesn't support js (I'm thinking about reader/tablet). We should see with them if this is a blocker or not (@tim-moody, @letompouce, other...)

**Comment by tim-moody** [comment]
If I understand correctly you are proposing a js wrapper, external to the zim content, which sounds like a good idea. I would call it kiwixClientScript.js or something less generic. We have struggled with browser compatibility and have gradually moved towards ECMA2015 or some such. The main thing we allow is flexbox.

**Comment by tim-moody** [comment]
I don't know if this is relevant, but for some time I have meant to report that there are js syntax and file not found errors in the chrome developer console for latest kiwix-serve and most zims:

```
Uncaught SyntaxError: Unexpected token '.'
jquery.js:141 JQMIGRATE: Migrate is installed with logging active, version 3.0.1
jquery.js:141 JQMIGRATE: jQuery is not compatible with Quirks Mode
migrateWarn @ jquery.js:141
(anonymous) @ jquery.js:142
(anonymous) @ jquery.js:140
(anonymous) @ jquery.js:140
jquery.js:153 Uncaught ReferenceError: mw is not defined
    at jquery.js:153
(anonymous) @ jquery.js:153
mediawiki.js:1 Uncaught ReferenceError: mw is not defined
    at mediawiki.js:1
(anonymous) @ mediawiki.js:1
site.js:1 Uncaught ReferenceError: mw is not defined
    at site.js:1
(anonymous) @ site.js:1
ext.cite.a11y.js:1 Uncaught ReferenceError: mediaWiki is not defined
    at ext.cite.a11y.js:1
(anonymous) @ ext.cite.a11y.js:1
```

**Comment by kelson42** [comment]
> I don't know if this is relevant, but for some time I have meant to report that there are js syntax and file not found errors in the chrome developer console for latest kiwix-serve and most zims

This is not related to kiwix-serve, but to the ZIM itself. So probably related to MWoffliner.

**Comment by rgaudin** [comment]
I also think @mgautierfr's suggestion is good. It would add a lot of flexibility and could foster contributions to this part which has received many requests over the years but is currently not that easy to hack on.

I'm not in favor of dropping no-js support though ; so that would mean injecting content to the page anyway…

* display the HTML-only part (what's currently in `body .kiwix`) of the taskbar (or even a simplified version) in a `<noscript />` tag.
* display a link plus css code hiding main content inside a `<noscript />` tag. the link would lead to that same page but letting libkiwix know it should include an oldstyle taskbark.

Not in favor of the latter as it would mean two different URLs for the same content.

What I don't like about any version is that it means two different ways to render the taskbar with one that we'll always forget to test and probably break.

**Comment by mgautierfr** [comment]
While #442 it technically fixing the issue, this discussion leads to some interesting question and potential improvement.
I'm not sure we should close this issue. Or maybe move my comment and the following one into a new issue.

**Comment by kelson42** [comment]
@mgautierfr Yes, I will create a new ticket with your comment.

**Comment by kelson42** [comment]
@mgautierfr Yes, see #443
