### ISSUE TITLE
Empty catalog/root.xml and catalog/search

### ISSUE THREAD

**Issue by MananJethwani** [kiwix/kiwix-lib#503]
while starting my kiwix-server with 
```
LD_LIBRARY_PATH=$(pwd)/BUILD_native_dyn/INSTALL/lib/x86_64-linux-gnu ./BUILD_native_dyn/INSTALL/bin/kiwix-serve -p 8000 <multiple zim files>
```
 and trying to access `http://localhost:8000/catalog/root.xml` and `http://localhost:8000/catalog/search` 
 I received the following response.
![Screenshot from 2021-05-07 00-40-30](https://user-images.githubusercontent.com/50267986/117352658-de3c7e80-aecc-11eb-9fe0-6283886ef321.png)
![Screenshot from 2021-05-07 00-40-37](https://user-images.githubusercontent.com/50267986/117352666-e0064200-aecc-11eb-9095-4f07c8337498.png)

but my homepage contains 6 zim files as you can see below.
![Screenshot from 2021-05-07 00-41-29](https://user-images.githubusercontent.com/50267986/117352758-fc09e380-aecc-11eb-8a81-8e735204e566.png)

**Comment by kelson42** [comment]
Might be the same as #500

**Comment by veloman-yunkan** [comment]
This behaviour is months old. `/catalog/root.xml` and `/catalog/search` endpoints return only those books that have both local path (`.local(true)`) and remote URL (`.local(true)`) defined: 

https://github.com/kiwix/kiwix-lib/blob/ab0ffb55bcbd7755867c6433838cc3ad3fd5d768/src/server/internalServer.cpp#L648

https://github.com/kiwix/kiwix-lib/blob/ab0ffb55bcbd7755867c6433838cc3ad3fd5d768/src/server/internalServer.cpp#L666

For a kiwix server started with ZIM files, there is no remote URL, that's why none of them are included in the results.

**Comment by kelson42** [comment]
@MananJethwani So I wa wrong, you have to create a library.xml with kiwix-manage and set the url= attribute, then it should work.
