### ISSUE TITLE
Wrong redirection handling

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#70]
Currently the kiwix-lib, if a redirect is found, search the target and return the target page body. It works so far the targeted page is at the same path level like the redirect. If not all relative URLs will probably fail to load properly.

As a workaround, in kiwix-serve a <base> node as been introduced, but this is not the proper answer to that problem and this fixes only kiwix-serve.

To fix that problem, probably the kiwix-lib should returns a proper code or HTML redirection code.

**Comment by mgautierfr** [comment]
> As a workaround, in kiwix-serve a node as been introduced, but this is not the proper answer to that problem and this fixes only kiwix-serve.

Hooo, that why the `base` node is for ? I was wondering why we add this node while rewriting the url in the document in the same time.

> To fix that problem, probably the kiwix-lib should returns a proper code or HTML redirection code.

I agree with this. Redirections are better handled on the client side.
But it is a bit tricky to do. It is a big API change as all clients assume that they will not get any redirection and directly get the content to display.

Until this issue is fixed, `kiwix-lib` has a method that return the content of the asked `url` but also the `baseUrl` (who is the url of real article used). This could be used to detect a redirection and fix url in the webview.
Sadly, this is not exposed in the JNI API. I can quickly add it (as I made it for the title argument https://github.com/kiwix/kiwix-lib/commit/d3acae1fd2bc56cfc38e005791eac2d9eba64b71)

**Comment by kelson42** [comment]
Yes, we should probably add a new parameter to the existing kiwix-lib method(s) to specificaly avoid to resolve redirects.

**Comment by okkebal** [comment]
The new run of StackExchange is being published to the Android version. The files show up in the "online" tab in "get content". So android users will start downloading and trying these files. Due to this issue the pages do not load correctly. This will be a bad experience for our users. The files should only be published in the Android version if they work in the Android version.

**Comment by automactic** [comment]
I think we just need to add something similar to `std::vector<std::string> getRedirectedURL(const std::string& url) const;`, but I know this might be easier said than done

**Comment by kelson42** [comment]
@automactic What would trigger this call? Would you call it each time you try to open an url?

**Comment by automactic** [comment]
@kelson42 I think so, yes, a call will be made every time opening a URL, since there is no way to tell if a url should redirect and every url could potentially redirect. 
-----
Another way to solve this is to get rid of redirections. Think of urls primary key of resources (html, css, js, etc) in a zim file. We resolve all the redirections during offline time.

**Comment by kelson42** [comment]
Done

**Comment by okkebal** [comment]
PS: the latest nightly for Android (2018-04-29) does not have this fix: Stack Exchange Zim files still render the same.... 

I guess you need to update a library?

**Comment by kelson42** [comment]
@okkebal Kiwix-Android needs to be updated (in version 3.0). Kiwix serve will be fixed this week IMO, Kiwix for iOS to be release in the next day is also fixed.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-xulrunner#508
