### ISSUE TITLE
Easy download of kiwix-lib dependences should be added to kiwix-lib

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-lib#9]
kiwix-lib should provide a way to download necessary dependences "quickly" (with an adhoc solution) from http://download.kiwix.org/dev/. This is the case with the "old" Kiwix download script and this simplify a lot the static compilation of kiwix(-lib). As a remember static0compilation is the "standard" compilation, non-static compilation is probably almost only needed for GNU/Linux distribution.

It seems that most of this code has been done in the kiwix-tools repo (for a reason which I ignore). This seems wrong to me, this should be done at kiwix-lib level, non kiwix-lib code should only bother of the kiwix-lib, not of kiwix-lib dependences.

See a related ticket in kiwix-tools https://github.com/kiwix/kiwix-tools/issues/8

**Comment by kelson42** [comment]
@mgautierfr  We have finally decided to put these things in "kiwix-build" repo. Can you please provide us a status on this, and maybe open/close necessary tickets?

**Comment by mgautierfr** [comment]
The script kiwix-builder.py in kiwix-tools has been moved in [kiwix-build](https://github.com/kiwix/kiwix-build) repository.

It allows download and compilation of all dependencies and "project" (kiwix-lib, kiwix-tools). (Tested on Fedora and Ubuntu 10.16)

**Comment by orblivion** [comment]
I'm just curious, what is the purpose of such a script? The reason that I'm trying to build Kiwix is to package it in a new system. As such, I want to be in charge of the dependencies in my own build script. When you make the Debian package, I would guess (not actually knowing the process) that they wouldn't want to package something that includes source pulled from the outside. They would want to use Debian's own copies of the dependencies.

So then, who is the "target market" for this easy build script? Is it for people trying to build the thing on a new platform? Or is it just for aspiring developers of Kiwix? Otherwise, I don't know why you wouldn't just download the binaries.

**Comment by mgautierfr** [comment]
Yes, if your packaging kiwix, you definitively not need this script and have to handle dependencies with your distribution package system.

This script is some kind of replacement for the `cd src/dependencies; make` in the kiwix repository.
This script is, as you suppose, for developers of Kiwix, aspiring or not :)
The idea is that the script becomes the standard way to start developing kiwix :
«Run the script and everything will be compiled, with the right version and options. Then you just have to patch kiwix*, run the script again and enjoy :)»
It will also handle cross-compilation for windows, android or arm systems.
I will also use it to compile the releases of kiwix in the future. (and so build the binaries the users will just download) 

(As a side note, I have a personal little preference to work on having kiwix available with [flatpack](http://flatpak.org/). It would allow us to make the work once and have kiwix available on almost all distributions)

**Comment by yekanchi** [comment]
I think this issue is neglected for a while, I wanted to build the kiwix-tools which need kiwix-lib package, then here has lots of dependencies and I want to build it for windows on windows and there I couldn't find any straight forward way to build the kiwix-lib for windows. and also I think the documentation for windows build is poor.

**Comment by mgautierfr** [comment]
This issue is not neglected. There is a whole repository for this : https://github.com/kiwix/kiwix-build

However, the build on windows is neglected. None of our developer are using windows. You can have a look at the kiwix-build's appveyor ci : https://github.com/kiwix/kiwix-build/blob/master/appveyor.yml and scripts in https://github.com/kiwix/kiwix-build/tree/master/appveyor to see how we build kiwix-desktop (and so kiwix-lib) on windows.
